services:
  backend:
    image: crpi-ff91b786rkkpt2fd.cn-guangzhou.personal.cr.aliyuncs.com/ai-novel-writing-assistant/ai-novel-writing-assistant:latest
    container_name: ai-novel-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      HOST: "0.0.0.0"
      DATABASE_URL: "file:/app/data/dev.db"
    volumes:
      - ai_novel_data:/app/data
      - ai_novel_logs:/app/logs

volumes:
  ai_novel_data:
  ai_novel_logs:
